{
 "title": "Pgpool-II",
 "tags": [ "pgpool" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "label": "environment", "query": { "query": "label_values(environment)" } },
   { "name": "ECSTaskID", "query": { "query": "label_values(taskId)" } }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgpool2_pool_nodes_status{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Active Connections Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgpool2_frontend_used_ratio{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connectios",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "pgpool2_frontend_used{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "pgpool2_frontend_total{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Replication delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pgpool2_pool_nodes_replication_delay{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    },
    {}
   ]
  },
  { "title": "Health Check Time Since Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Last Skip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_last_skip_health_check{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{taskId}} ({{role}})"
    }
   ]
  },
  {
   "title": "Last Successful",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_last_successful_health_check{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{taskId}} ({{role}})"
    }
   ]
  },
  {
   "title": "Last Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_last_failed_health_check{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{taskId}} ({{role}})"
    }
   ]
  },
  {
   "title": "Last HealthCheck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_last_health_check{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{taskId}} ({{role}})"
    }
   ]
  },
  { "title": "Error Message Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Error Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_error_cnt{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{taskId}} ({{role}}) ({{role}})"
    }
   ]
  },
  {
   "title": "Fatal Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 25 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_fatal_cnt{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{taskId}} ({{role}})"
    }
   ]
  },
  {
   "title": "Panic Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 25 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_panic_cnt{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{taskId}} ({{role}})"
    }
   ]
  },
  { "title": "SQL Command Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "SELECT statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_select_cnt{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "DELETE statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 34 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_delete_cnt{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Other statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 34 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_other_cnt{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "UPDATE statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_update_cnt{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "DDL statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 40 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_ddl_cnt{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "INSERT statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 40 },
   "targets": [
    {
     "expr": "pgpool2_pool_backend_stats_insert_cnt{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Number of health check count in total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_total_count{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of Successful Health Check ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 47 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_success_count{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of failed health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_fail_count{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of skipped health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_skip_count{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Maximum health check duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_max_duration{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of maximum retried health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_max_retry_count{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of average retried health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 52 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_average_retry_count{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Average health check duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_average_duration{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Minimum health check duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_min_duration{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  {
   "title": "Number of retried health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "pgpool2_pool_health_check_stats_retry_count{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "{{hostname}} ({{role}})"
    }
   ]
  },
  { "title": "Query Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Query Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgpool2_pool_cache_cache_hit_ratio{taskId=~\"$ECSTaskID\", environment=\"$Environment\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}